### ISSUE TITLE
Cannot download dataset

### ISSUE THREAD

**Issue by pboudoin** [seralexger/clothing-detection-ecommerce-dataset#1]
Hi,

I can't download dataset on mega upload. I encounter this error:
`MEGA failed to load because 

The file "lang/fr_4989654129f838d5ae9d1a06246b3ed9452a0fec712860323912bb57696727ef.json" could not be loaded.`

Could you provide it on another platform please?

**Comment by seralexger** [comment]
I have checked the "dastaset.zip" download and it works fine. I close the issue.
